### ISSUE TITLE
Hide the broken image if the plugin failed to get the social media image

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#331]
Some web would reject the request for image (403), and there would be a broken image icon:
![image](https://github.com/user-attachments/assets/2e181172-ec3b-405e-8018-198904002e97)

In the DevTool:
![image](https://github.com/user-attachments/assets/ea5aecc3-9cce-48a4-abd6-21c1e69e83f5)

So, could you consider ignore the "bad image" if the response fails?

---

BTW, v1.42.0 is a huge update! Really love it, good job!

**Comment by decaf-dev** [comment]
@Moyf Sorry for the hiatus. I have been busy working on other things. Yes, I can fix that today. Expect another big update coming soon!

**Comment by decaf-dev** [comment]
Should be fixed in 1.43.1. Let me know if it still causes you issues.

**Comment by Moyf** [comment]
![image](https://github.com/user-attachments/assets/1b8aae88-3f1f-4a7e-b6e8-22afd60a3fb5)

Updated to 1.44 and still see the broken image:
![image](https://github.com/user-attachments/assets/00c1aba7-355e-4cd5-b9cb-cc744e314797)

> I've tried the "Clear cache" button in the setting page.


Here is one of the URL with broken image, in case you need to test:
`https://cp.cc1234.cc/#stories`

---

My settings:
![image](https://github.com/user-attachments/assets/ca02998f-af50-4a4e-89d2-a830471bf750)

**Comment by Moyf** [comment]
Oh, by the way, I wanted to share a video I came across a few days ago:  
https://www.youtube.com/watch?v=9mVHCnie4Lo  

I'm not certain if it will be helpful, but I hope it can assist you! :)

**Comment by decaf-dev** [comment]
That's very odd. I do not get a broken image for that link.

**Comment by decaf-dev** [comment]
I do see that it doesn't have a social media image though.

<img width="376" alt="image" src="https://github.com/user-attachments/assets/9b7b1aec-690a-4abc-b38d-82a8149b2025">

**Comment by decaf-dev** [comment]
Could you set your plugin log level to `Trace` in the settings and then open vault explorer and give me a screenshot like the one I just sent?

**Comment by Moyf** [comment]
hmm, interesting, I didn't see the url:
![image](https://github.com/user-attachments/assets/bcdc33cf-18fc-41ca-a5cb-8a03b263cb19)

Oh, actually the broken image is a "app://"
![image](https://github.com/user-attachments/assets/85bae5ec-8b8a-4789-af1d-0325aa22f428)


`src="app://71c3320d386de07c857d37f347589d5259d6/H:/Docs/Obsinote/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/Obsidian/Plugins/Assets/comp-tool-%E7%BB%9F%E8%AE%A1%E5%B0%8F%E7%BB%84%E4%BB%B6.components?1722218406158"`

The related logs:
![image](https://github.com/user-attachments/assets/a4a53a33-28ec-4fdd-818c-17bc3b824e2a)


And the page..

WAIT A MINUTE I THINK I FOUND OUT WHY!
![image](https://github.com/user-attachments/assets/b40e1a73-37cf-4cf1-96d9-cfbe9e2ac29f)

It contains some specific attachment ( `xx.components` ) and it's not image!

And this is wrongly recognized as a "image" and the render failed!

It's not related to "Social Media Image" (Sorry I think it wront), but the `![[xxx.comopnent]]` file in page.

**Comment by decaf-dev** [comment]
So the url: https://cp.cc1234.cc/#stories doesn't create a broken image?

**Comment by decaf-dev** [comment]
Gotcha. I will check this out.
